export const SHIP_TYPES = {
    SLOOP: {
        name: 'Sloop',
        size: 40,
        speed: 200,
        rowing: 0,
        turnSpeed: 200,
        cannons: 2,
        crew: 60,
        crewMax: 60,
        cargo: 0,
        cargoMax: 300,
        windResistance: 0.8,
        color: 0x8B4513
    },
    BRIGANTINE: {
        name: 'Brigantine',
        size: 50,
        speed: 150,
        rowing: 0,
        turnSpeed: 160,
        cannons: 4,
        crew: 75,
        crewMax: 75,
        cargo: 0,
        cargoMax: 500,
        windResistance: 0.7,
        color: 0x654321
    },

    FRIGATE: {
        name: 'Frigate',
        size: 60,
        speed: 180,
        rowing: 0,
        turnSpeed: 180,
        cannons: 6,
        crew: 150,
        crewMax: 150,
        cargo: 0,
        cargoMax: 750,
        windResistance: 0.7,
        color: 0x4B2E2E
    },
    GALLEON: {
        name: 'Galleon',
        size: 70,
        speed: 100,
        rowing: 0,
        turnSpeed: 120,
        cannons: 8,
        crew: 150,
        crewMax: 150,
        cargo: 0,
        cargoMax: 1000,
        windResistance: 0.6,
        color: 0x5C4033
    },
    CLIPPER: {
        name: 'Clipper',
        size: 60,
        speed: 175,
        rowing: 0,
        turnSpeed: 100,
        cannons: 2,
        crew: 100,
        crewMax: 100,
        cargo: 0,
        cargoMax: 1500,
        windResistance: 0.9,
        color: 0x5C4033
    },
    FIRST_RATE: {
        name: 'First_Rate',
        size: 100,
        speed: 75,
        rowing: 0,
        turnSpeed: 80,
        cannons: 12,
        crew: 800,
        crewMax: 800,
        cargo: 0,
        cargoMax: 2500,
        windResistance: 0.6,
        color: 0x5C4033
    },
    SLOOP_OF_WAR:{
        name:'Sloop_of_War',
        size: 60,
        speed: 150,
        rowing: 0,
        turnSpeed: 165,
        cannons: 10,
        crew: 200,
        crewMax: 200,
        cargo: 0,
        cargoMax: 1250,
        windResistance: 0.75,
        color: 0x5C4033
    },
    GALLEY:{
        name: 'Galley',
        size: 75,
        speed: 100,
        rowing: 100,
        turnSpeed: 125,
        cannons: 4,
        crew: 200,
        crewMax:200,
        cargo: 0,
        cargoMax: 1250,
        windResistance: 0.7,
        color: 0x5C4033,     
    }
};
